{
  "formatVersion": "1.1",
  "component": {
    "group": "com.guodong.android",
    "module": "mask-api-kt",
    "version": "0.0.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.5.1",
      "buildId": "2h6fomk7tzbvfhodjwudth3wvi"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "mask-api-kt-0.0.3.jar",
          "url": "mask-api-kt-0.0.3.jar",
          "size": 1791,
          "sha512": "d126b667fedadcc039f822fb259c7cd514110a67942bdf25fd9917853667b31eb56401a767cd98eb8522c0af0943aa6625336bb61209d2160b114f367f23238e",
          "sha256": "874f073a35c98cffccc8bbfddc64bf445a98f72e74f1b48c06a40b7c0cd9a65f",
          "sha1": "77adbc6f223b48779f59e24fb96cb7ac036fabec",
          "md5": "4c6b43a25957d3645d632ec763249850"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.6.10"
          }
        }
      ],
      "files": [
        {
          "name": "mask-api-kt-0.0.3.jar",
          "url": "mask-api-kt-0.0.3.jar",
          "size": 1791,
          "sha512": "d126b667fedadcc039f822fb259c7cd514110a67942bdf25fd9917853667b31eb56401a767cd98eb8522c0af0943aa6625336bb61209d2160b114f367f23238e",
          "sha256": "874f073a35c98cffccc8bbfddc64bf445a98f72e74f1b48c06a40b7c0cd9a65f",
          "sha1": "77adbc6f223b48779f59e24fb96cb7ac036fabec",
          "md5": "4c6b43a25957d3645d632ec763249850"
        }
      ]
    }
  ]
}
