{
  "formatVersion": "1.1",
  "component": {
    "group": "com.guodongandroid",
    "module": "widgets",
    "version": "1.0-alpha01",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.0.2"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-1.0-alpha01.aar",
          "url": "widgets-1.0-alpha01.aar",
          "size": 19251,
          "sha512": "12aec16eba42b20093c12456cba529e941c0b38440aaa89d9cddc90ae6793c851dc88ff5c3afed2d0e949c95f286b90c6aa982a09133d869044bbf95447ea5cb",
          "sha256": "f0656fea8954e337886122705061d4de62960eee78e43c82f9e9a2ad6ddf8bfc",
          "sha1": "175c38f84c84d97d688b55aaef4e79e07124ae4a",
          "md5": "289c3443d383f6f6101d4f6cb9d88e14"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "androidx.appcompat",
          "module": "appcompat",
          "version": {
            "requires": "1.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "widgets-1.0-alpha01.aar",
          "url": "widgets-1.0-alpha01.aar",
          "size": 19251,
          "sha512": "12aec16eba42b20093c12456cba529e941c0b38440aaa89d9cddc90ae6793c851dc88ff5c3afed2d0e949c95f286b90c6aa982a09133d869044bbf95447ea5cb",
          "sha256": "f0656fea8954e337886122705061d4de62960eee78e43c82f9e9a2ad6ddf8bfc",
          "sha1": "175c38f84c84d97d688b55aaef4e79e07124ae4a",
          "md5": "289c3443d383f6f6101d4f6cb9d88e14"
        }
      ]
    }
  ]
}
